
name: Build Developer Images

on:
  push:
    branches: [ main ]

jobs:
  list-manifests-base:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v3
      - id: set-matrix
        run: echo "::set-output name=matrix::$(ls base | jq -R -s -c 'split("\n")[:-1]')"

  build_base_image:
    name: Build and publish base image to Quay.io
    runs-on: ubuntu-20.04
    needs: list-manifests-base
    strategy:
      fail-fast: false
      matrix:
        manifest: ${{ fromJson(needs.list-manifests-base.outputs.matrix) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            quay.io/webcenter/developer-image
          flavor: |
            latest=true
            prefix=base-${{ matrix.manifest }}-,onlatest=true
          tags: |
            type=ref,event=branch,prefix=base-${{ matrix.manifest }}-
            type=ref,event=tag,prefix=base-${{ matrix.manifest }}-
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: base/${{ matrix.manifest }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
